export enum TileType {
    ENTRANCE = "entrance",
    SANCTUM = "sanctum", 
    WEST_WING = "west_wing",
    EAST_WING = "east_wing",
    SAFE = "safe",
    FIRE_4_WAY = "fire_4_way",
    FIRE_T_JUNCTION = "fire_t_junction",
    CAVE_IN_1 = "cave_in_1",
    CAVE_IN_2 = "cave_in_2",
    CAVE_IN_3 = "cave_in_3",
    CAVE_IN_4 = "cave_in_4",
    CAVE_IN_5 = "cave_in_5",
    CAVE_IN_6 = "cave_in_6",
    GUARDIAN_L_JUNCTION = "guardian_l_junction",
    GUARDIAN_DEAD_END = "guardian_dead_end",
    SPIKE_TRAP = "spike_trap",
    DART_TRAP = "dart_trap",
    BRIDGE = "bridge",
    KEY_CHAMBER = "key_chamber"
}